// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKO4eg6f99oH5yWSl5cVKQ9kP6ghklxvo',
    appId: '1:721292780410:android:79045a6448f3f2f62c6cc3',
    messagingSenderId: '721292780410',
    projectId: 'shoply-7ec3e',
    storageBucket: 'shoply-7ec3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL9rYGqb80_UeoDAMpZrVaglWcqkTcpbg',
    appId: '1:721292780410:ios:698705e5ecff03cd2c6cc3',
    messagingSenderId: '721292780410',
    projectId: 'shoply-7ec3e',
    storageBucket: 'shoply-7ec3e.appspot.com',
    iosBundleId: 'com.example.shoply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL9rYGqb80_UeoDAMpZrVaglWcqkTcpbg',
    appId: '1:721292780410:ios:698705e5ecff03cd2c6cc3',
    messagingSenderId: '721292780410',
    projectId: 'shoply-7ec3e',
    storageBucket: 'shoply-7ec3e.appspot.com',
    iosBundleId: 'com.example.shoply',
  );

}